"""
hypersecure_password_platform.py
=================================
HYPER-SECURE ENTERPRISE PASSWORD VALIDATION PLATFORM — v2.0
Generated by: SecurePass Architect Prompt
Tested on:    Python 3.11+
Dependencies: Zero — stdlib only

Fixes applied vs v1.0
---------------------
  Fix A — Sequential patterns expanded: full a–z + reversed (cba, zyx) + reversed digits (321, 098)
  Fix B — Keyboard patterns expanded: reversed walks, numpad, gaming keys (wasd)
  Fix C — Common password list grown from 14 → 50+ entries
  Fix D — Unicode entropy: charset_size now adds +1000 when unicode chars present
  Fix E — YEAR_PATTERN added to score penalty table (−10)
  Fix F — _validate_year_patterns() new method; catches 19xx/20xx embedded in password
"""

from __future__ import annotations

import math
import re
import unicodedata
from dataclasses import dataclass
from enum import Enum
from typing import Final, FrozenSet, List, Optional, Sequence, Tuple


# =============================================================================
# ENUMS
# =============================================================================

class Severity(str, Enum):
    LOW      = "LOW"
    MEDIUM   = "MEDIUM"
    HIGH     = "HIGH"
    CRITICAL = "CRITICAL"


class StrengthLevel(str, Enum):
    VERY_WEAK   = "VERY_WEAK"
    WEAK        = "WEAK"
    FAIR        = "FAIR"
    GOOD        = "GOOD"
    STRONG      = "STRONG"
    VERY_STRONG = "VERY_STRONG"


# =============================================================================
# MODELS
# =============================================================================

@dataclass(frozen=True, slots=True)
class ValidationIssue:
    """A single structured validation finding."""
    code:     str
    message:  str
    severity: Severity


@dataclass(frozen=True, slots=True)
class PasswordPolicy:
    """
    Immutable enterprise password policy.
    All fields have safe production defaults.
    """
    min_length:                int  = 12
    max_length:                int  = 128
    require_uppercase:         bool = True
    require_lowercase:         bool = True
    require_numbers:           bool = True
    require_special:           bool = True
    allow_unicode:             bool = True
    allow_spaces:              bool = False
    check_common_passwords:    bool = True
    check_keyboard_patterns:   bool = True
    check_sequential_patterns: bool = True
    check_repeated_patterns:   bool = True
    check_year_patterns:       bool = True   # Fix F — new policy flag
    max_consecutive_repeats:   int  = 2
    minimum_strength_score:    int  = 60
    special_characters:        str  = "!@#$%^&*()-_=+[]{};:,.<>?/|"

    def __post_init__(self) -> None:
        if self.min_length < 1:
            raise ValueError("min_length must be >= 1")
        if self.max_length < self.min_length:
            raise ValueError("max_length must be >= min_length")
        if not (0 <= self.minimum_strength_score <= 100):
            raise ValueError("minimum_strength_score must be between 0 and 100")
        if self.max_consecutive_repeats < 1:
            raise ValueError("max_consecutive_repeats must be >= 1")


@dataclass(frozen=True, slots=True)
class PasswordProfile:
    """Cached per-password character analysis. Built once, reused across all validators."""
    password:          str
    length:            int
    has_uppercase:     bool
    has_lowercase:     bool
    has_digit:         bool
    has_special:       bool
    has_unicode:       bool
    has_whitespace:    bool
    unique_characters: int
    charset_size:      int
    entropy_bits:      float


@dataclass(frozen=True, slots=True)
class PasswordAnalysis:
    """Final immutable report returned from validate()."""
    valid:        bool
    score:        int
    strength:     StrengthLevel
    entropy_bits: float
    issues:       Tuple[ValidationIssue, ...]
    profile:      PasswordProfile


# =============================================================================
# VALIDATOR
# =============================================================================

class HyperSecurePasswordValidator:
    """
    Principal-level password validator.
    Stateless and thread-safe — holds no mutable state after __init__.
    """

    # Fix C — expanded from 14 to 50+ entries
    COMMON_PASSWORDS: Final[FrozenSet[str]] = frozenset({
        "password", "password1", "password123", "password1234",
        "admin", "admin123", "admin1234", "administrator",
        "qwerty", "qwerty123", "qwertyuiop",
        "123456", "1234567", "12345678", "123456789", "1234567890",
        "welcome", "welcome1", "welcome123",
        "letmein", "letmein1",
        "abc123", "abcdef",
        "passw0rd", "p@ssword", "p@ssw0rd", "pa$$word",
        "changeme", "changeme123",
        "root", "root123",
        "guest", "guest123",
        "login", "login123",
        "dragon", "master", "monkey", "shadow",
        "sunshine", "princess", "baseball", "football",
        "superman", "batman", "trustno1",
        "iloveyou", "iloveyou1",
        "michael", "jessica", "ashley", "jennifer",
        "2024", "2025", "2026",
    })

    # Fix B — expanded: upper row variants, numpad, gaming keys, reversed walks
    KEYBOARD_PATTERNS: Final[Tuple[str, ...]] = (
        # Top row — forward
        "qwerty", "qwertyuiop", "werty", "erty", "rtyuiop",
        # Home row — forward
        "asdfgh", "asdfghjkl", "sdfgh", "dfghj",
        # Bottom row — forward
        "zxcvbn", "xcvbn",
        # Number row — forward
        "12345", "23456", "34567", "45678", "56789", "67890",
        # Diagonal walks
        "1qaz", "2wsx", "3edc", "4rfv", "qazwsx", "qazxsw",
        # Numpad patterns
        "789456123", "147258369",
        # Gaming
        "wasd", "wsad",
        # Reversed walks — Fix B
        "ytrewq", "fdsa", "lkjhg", "nbvcxz",
    )

    # Fix A — full a–z + reversed alpha + full 0–9 + reversed digits
    SEQUENTIAL_PATTERNS: Final[Tuple[str, ...]] = (
        # Forward alpha
        "abc", "bcd", "cde", "def", "efg", "fgh", "ghi", "hij", "ijk",
        "jkl", "klm", "lmn", "mno", "nop", "opq", "pqr", "qrs", "rst",
        "stu", "tuv", "uvw", "vwx", "wxy", "xyz",
        # Reversed alpha — Fix A
        "cba", "dcb", "edc", "fed", "gfe", "hgf", "ihg", "jih",
        "zyx", "yxw", "xwv", "wvu", "vut", "uts", "tsr", "srq",
        # Forward digits
        "123", "234", "345", "456", "567", "678", "789", "890",
        # Reversed digits — Fix A
        "321", "432", "543", "654", "765", "876", "987", "098",
    )

    # Fix F — year pattern detector; use re.Pattern[str] directly (typing.Pattern deprecated 3.9+)
    YEAR_PATTERN:      Final[re.Pattern[str]] = re.compile(r"(19|20)\d{2}")
    WHITESPACE_PATTERN: Final[re.Pattern[str]] = re.compile(r"\s")

    def __init__(self, policy: Optional[PasswordPolicy] = None) -> None:
        self.policy = policy or PasswordPolicy()
        self._special_pattern: re.Pattern[str] = re.compile(
            f"[{re.escape(self.policy.special_characters)}]"
        )

    # =========================================================================
    # PUBLIC API
    # =========================================================================

    def validate(self, password: Optional[str]) -> PasswordAnalysis:
        """Validate password and return a full immutable PasswordAnalysis report."""
        if password is None:
            return self._build_failed_result(
                ValidationIssue("NULL_PASSWORD", "Password cannot be None", Severity.CRITICAL)
            )
        if not isinstance(password, str):
            return self._build_failed_result(
                ValidationIssue("INVALID_TYPE", "Password must be a string", Severity.CRITICAL)
            )

        # Normalise to NFKC before any analysis
        password = unicodedata.normalize("NFKC", password)
        profile  = self._build_profile(password)

        issues: List[ValidationIssue] = []
        issues.extend(self._validate_length(profile))
        issues.extend(self._validate_character_classes(profile))
        issues.extend(self._validate_unicode(profile))
        issues.extend(self._validate_whitespace(profile))
        issues.extend(self._validate_common_passwords(profile))
        issues.extend(self._validate_keyboard_patterns(profile))
        issues.extend(self._validate_sequential_patterns(profile))
        issues.extend(self._validate_repeated_patterns(profile))
        issues.extend(self._validate_year_patterns(profile))   # Fix F

        score    = self._calculate_strength_score(profile, issues)
        strength = self._map_strength(score)

        if score < self.policy.minimum_strength_score:
            issues.append(ValidationIssue(
                "STRENGTH_TOO_LOW",
                "Password strength below required threshold",
                Severity.HIGH,
            ))

        return PasswordAnalysis(
            valid=len(issues) == 0,
            score=score,
            strength=strength,
            entropy_bits=profile.entropy_bits,
            issues=tuple(issues),
            profile=profile,
        )

    # =========================================================================
    # PROFILE ENGINE
    # =========================================================================

    def _build_profile(self, password: str) -> PasswordProfile:
        """Build a cached character analysis profile for the password."""
        has_upper  = any(c.isupper() for c in password)
        has_lower  = any(c.islower() for c in password)
        has_digit  = any(c.isdigit() for c in password)
        has_spec   = bool(self._special_pattern.search(password))
        has_uni    = any(ord(c) > 127 for c in password)
        has_ws     = bool(self.WHITESPACE_PATTERN.search(password))

        charset_size = 0
        if has_lower:  charset_size += 26
        if has_upper:  charset_size += 26
        if has_digit:  charset_size += 10
        if has_spec:   charset_size += len(self.policy.special_characters)
        if has_uni:    charset_size += 1000  # Fix D — unicode entropy pool

        return PasswordProfile(
            password=password,
            length=len(password),
            has_uppercase=has_upper,
            has_lowercase=has_lower,
            has_digit=has_digit,
            has_special=has_spec,
            has_unicode=has_uni,
            has_whitespace=has_ws,
            unique_characters=len(set(password)),
            charset_size=charset_size,
            entropy_bits=self._calculate_entropy(password, charset_size),
        )

    # =========================================================================
    # VALIDATION RULES
    # =========================================================================

    def _validate_length(self, p: PasswordProfile) -> List[ValidationIssue]:
        issues: List[ValidationIssue] = []
        if p.length < self.policy.min_length:
            issues.append(ValidationIssue(
                "PASSWORD_TOO_SHORT",
                f"Length {p.length} is below minimum {self.policy.min_length}",
                Severity.HIGH,
            ))
        if p.length > self.policy.max_length:
            issues.append(ValidationIssue(
                "PASSWORD_TOO_LONG",
                f"Length {p.length} exceeds maximum {self.policy.max_length}",
                Severity.MEDIUM,
            ))
        return issues

    def _validate_character_classes(self, p: PasswordProfile) -> List[ValidationIssue]:
        issues: List[ValidationIssue] = []
        checks = [
            (self.policy.require_uppercase, p.has_uppercase,
             "MISSING_UPPERCASE", "Missing uppercase letter"),
            (self.policy.require_lowercase, p.has_lowercase,
             "MISSING_LOWERCASE", "Missing lowercase letter"),
            (self.policy.require_numbers,   p.has_digit,
             "MISSING_NUMBER",    "Missing numeric digit"),
            (self.policy.require_special,   p.has_special,
             "MISSING_SPECIAL",   "Missing special character"),
        ]
        for required, present, code, message in checks:
            if required and not present:
                issues.append(ValidationIssue(code, message, Severity.MEDIUM))
        return issues

    def _validate_unicode(self, p: PasswordProfile) -> List[ValidationIssue]:
        if not self.policy.allow_unicode and p.has_unicode:
            return [ValidationIssue(
                "UNICODE_NOT_ALLOWED",
                "Unicode characters are not permitted by policy",
                Severity.MEDIUM,
            )]
        return []

    def _validate_whitespace(self, p: PasswordProfile) -> List[ValidationIssue]:
        if not self.policy.allow_spaces and p.has_whitespace:
            return [ValidationIssue(
                "WHITESPACE_NOT_ALLOWED",
                "Whitespace characters are not permitted by policy",
                Severity.MEDIUM,
            )]
        return []

    def _validate_common_passwords(self, p: PasswordProfile) -> List[ValidationIssue]:
        if (
            self.policy.check_common_passwords
            and p.password.lower() in self.COMMON_PASSWORDS
        ):
            return [ValidationIssue(
                "COMMON_PASSWORD",
                "Password appears in the common password blocklist",
                Severity.CRITICAL,
            )]
        return []

    def _validate_keyboard_patterns(self, p: PasswordProfile) -> List[ValidationIssue]:
        if not self.policy.check_keyboard_patterns:
            return []
        pw_lower = p.password.lower()
        for pattern in self.KEYBOARD_PATTERNS:
            if pattern in pw_lower:
                return [ValidationIssue(
                    "KEYBOARD_PATTERN",
                    "Password contains a keyboard walk pattern",
                    Severity.HIGH,
                )]
        return []

    def _validate_sequential_patterns(self, p: PasswordProfile) -> List[ValidationIssue]:
        if not self.policy.check_sequential_patterns:
            return []
        pw_lower = p.password.lower()
        for pattern in self.SEQUENTIAL_PATTERNS:
            if pattern in pw_lower:
                return [ValidationIssue(
                    "SEQUENTIAL_PATTERN",
                    "Password contains a sequential character pattern",
                    Severity.HIGH,
                )]
        return []

    def _validate_repeated_patterns(self, p: PasswordProfile) -> List[ValidationIssue]:
        if not self.policy.check_repeated_patterns:
            return []
        count = 1
        for i in range(1, p.length):
            if p.password[i] == p.password[i - 1]:
                count += 1
                if count > self.policy.max_consecutive_repeats:
                    return [ValidationIssue(
                        "REPEATED_PATTERN",
                        f"Password has more than {self.policy.max_consecutive_repeats} "
                        "consecutive identical characters",
                        Severity.MEDIUM,
                    )]
            else:
                count = 1
        return []

    def _validate_year_patterns(self, p: PasswordProfile) -> List[ValidationIssue]:
        """Fix F — detects predictable year suffixes such as 1999, 2024, 2026."""
        if not self.policy.check_year_patterns:
            return []
        if self.YEAR_PATTERN.search(p.password):
            return [ValidationIssue(
                "YEAR_PATTERN",
                "Password contains a predictable year (e.g. 2026)",
                Severity.MEDIUM,
            )]
        return []

    # =========================================================================
    # STRENGTH ENGINE
    # =========================================================================

    def _calculate_entropy(self, password: str, charset_size: int) -> float:
        """Shannon-style entropy estimate: length × log2(charset_size)."""
        if not password or charset_size == 0:
            return 0.0
        return round(len(password) * math.log2(charset_size), 2)

    def _calculate_strength_score(
        self,
        profile: PasswordProfile,
        issues: Sequence[ValidationIssue],
    ) -> int:
        """Compute 0–100 strength score with bonuses and penalties."""
        score = 0

        # Length bonus
        if profile.length >= 24:    score += 35
        elif profile.length >= 18:  score += 30
        elif profile.length >= 14:  score += 25
        elif profile.length >= 12:  score += 20

        # Character diversity bonus
        diversity = sum([
            profile.has_uppercase,
            profile.has_lowercase,
            profile.has_digit,
            profile.has_special,
        ])
        score += diversity * 10

        # Entropy bonus
        if profile.entropy_bits >= 120:   score += 25
        elif profile.entropy_bits >= 90:  score += 20
        elif profile.entropy_bits >= 70:  score += 15
        elif profile.entropy_bits >= 50:  score += 10

        # Uniqueness bonus
        uniqueness_ratio = profile.unique_characters / max(1, profile.length)
        if uniqueness_ratio >= 0.8:
            score += 10

        # Penalties
        penalties: dict[str, int] = {
            "COMMON_PASSWORD":    50,
            "PASSWORD_TOO_SHORT": 25,
            "KEYBOARD_PATTERN":   20,
            "SEQUENTIAL_PATTERN": 15,
            "REPEATED_PATTERN":   10,
            "YEAR_PATTERN":       10,   # Fix E
        }
        for issue in issues:
            score -= penalties.get(issue.code, 5)

        return max(0, min(100, score))

    def _map_strength(self, score: int) -> StrengthLevel:
        if score >= 90: return StrengthLevel.VERY_STRONG
        if score >= 75: return StrengthLevel.STRONG
        if score >= 60: return StrengthLevel.GOOD
        if score >= 40: return StrengthLevel.FAIR
        if score >= 20: return StrengthLevel.WEAK
        return StrengthLevel.VERY_WEAK

    # =========================================================================
    # INTERNAL HELPERS
    # =========================================================================

    def _build_failed_result(self, issue: ValidationIssue) -> PasswordAnalysis:
        """Return a zero-score failed analysis for pre-pipeline guards."""
        empty_profile = PasswordProfile(
            password="", length=0,
            has_uppercase=False, has_lowercase=False,
            has_digit=False, has_special=False,
            has_unicode=False, has_whitespace=False,
            unique_characters=0, charset_size=0, entropy_bits=0.0,
        )
        return PasswordAnalysis(
            valid=False, score=0,
            strength=StrengthLevel.VERY_WEAK,
            entropy_bits=0.0,
            issues=(issue,),
            profile=empty_profile,
        )


# =============================================================================
# CONVENIENCE API
# =============================================================================

_default_validator = HyperSecurePasswordValidator()


def validate_password(password: str) -> bool:
    """Return True only if password passes all policy checks."""
    return _default_validator.validate(password).valid


def analyze_password(password: str) -> PasswordAnalysis:
    """Return a full structured PasswordAnalysis report."""
    return _default_validator.validate(password)


# =============================================================================
# DEMO
# =============================================================================

if __name__ == "__main__":
    validator = HyperSecurePasswordValidator()

    test_passwords = [
        "weak",
        "password123",
        "Qwerty123!",
        "StrongPass#2026",
        "UltraSecure#Enterprise2026!",
        "MyUltra$Secure#BankingPass!",
        "Ünïcödé#Páss!Extra",
        None,
    ]

    print("=" * 72)
    print("  HYPER-SECURE ENTERPRISE PASSWORD PLATFORM v2.0")
    print("=" * 72)

    for pw in test_passwords:
        report = validator.validate(pw)
        print(f"\n  Password : {pw!r}")
        print(f"  Valid    : {report.valid}  |  Score: {report.score}/100  |  {report.strength.value}")
        print(f"  Entropy  : {report.entropy_bits} bits  |  "
              f"Length: {report.profile.length}  |  "
              f"Unique chars: {report.profile.unique_characters}")
        if report.issues:
            print("  Issues:")
            for issue in report.issues:
                print(f"    [{issue.severity.value:<8}] {issue.code}: {issue.message}")
        else:
            print("  ✓ No issues — password passed all checks")
        print("  " + "-" * 68)
